# https://taskfile.dev
version: "3"
tasks:
  setup:
    cmds:
      - task: install-asdf-ruby
      - task: install-gems

  install-asdf-ruby:
    desc: install ruby by great ASDF
    status:
      - test -f ~/.asdf/shims/ruby
    cmds:
      - asdf plugin add ruby || true
      - asdf install ruby 3.3.2
      - asdf global ruby 3.3.2
      - ruby --version

  install-gems:
    desc: install commonly used gems
    status:
      - thor -v
    cmds:
      - gem install thor
